### ISSUE TITLE
Parsing of xdot output fails for strict graphs 

### ISSUE THREAD

**Issue by magjac** [mstefaniuk/graph-viz-d3-js#28]
The strict example from http://www.graphviz.org/content/dot-language fails:
```
strict graph { 
  a -- b
  a -- b
  b -- a [color=blue]
} 
```

**Comment by magjac** [comment]
Thanks for the fast fix :-). I guess http://graphviz.it is not yet updated since it still fails there.

I can't test locally yet since I'm still struggling to get bower running on Ubuntu 14.04.

**Comment by mstefaniuk** [comment]
Website has been fixed today, just now.

**Comment by magjac** [comment]
Thanks, but the attached example still doesn't work.

[sofia.txt](https://github.com/mstefaniuk/graph-viz-d3-js/files/843584/sofia.txt)

Removing the "strict" keyword makes it work again.

**Comment by mstefaniuk** [comment]
Heh, fixed also for digraphs. Already online.
